[package]
name = "runtime-browser"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
runtime-dom = { path = "../runtime-dom" }
runtime-network = { path = "../runtime-network" }
runtime-js = { path = "../runtime-js", default-features = false, features = ["v8"] }
tokio = { workspace = true, features = ["rt-multi-thread","time","sync"] }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
