[package]
name = "runtime-core"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
runtime-observability = { path = "../runtime-observability" }
runtime-sandbox = { path = "../runtime-sandbox" }
runtime-policy = { path = "../runtime-policy" }
runtime-auth = { path = "../runtime-auth" }
uuid = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
runtime-interaction = { path = "../runtime-interaction" }
anyhow = { workspace = true }
